"""initial schema

Revision ID: d95fc7d10b23
Revises:
Create Date: 2026-07-23 20:29:05.211286
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d95fc7d10b23"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manufacturers",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturers")),
        sa.UniqueConstraint("name", name=op.f("uq_manufacturers_name")),
    )
    op.create_table(
        "providers",
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
        sa.UniqueConstraint("slug", name=op.f("uq_providers_slug")),
    )
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("manufacturer_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturers.id"],
            name=op.f("fk_brands_manufacturer_id_manufacturers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("manufacturer_id", "name", name=op.f("uq_brands_manufacturer_id_name")),
    )
    op.create_table(
        "documents",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("source_reference", sa.String(length=500), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("revision", sa.String(length=50), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["providers.id"], name=op.f("fk_documents_provider_id_providers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint(
            "provider_id",
            "source_reference",
            name=op.f("uq_documents_provider_id_source_reference"),
        ),
    )
    op.create_index(
        op.f("ix_documents_document_type"), "documents", ["document_type"], unique=False
    )
    op.create_table(
        "machine_models",
        sa.Column("model_number", sa.String(length=100), nullable=False),
        sa.Column("brand_id", sa.Uuid(), nullable=False),
        sa.Column("machine_type", sa.String(length=100), nullable=True),
        sa.Column("family", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_machine_models_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_machine_models")),
        sa.UniqueConstraint(
            "brand_id", "model_number", name=op.f("uq_machine_models_brand_id_model_number")
        ),
    )
    op.create_index(
        op.f("ix_machine_models_model_number"), "machine_models", ["model_number"], unique=False
    )
    op.create_table(
        "model_documents",
        sa.Column("machine_model_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_model_documents_document_id_documents")
        ),
        sa.ForeignKeyConstraint(
            ["machine_model_id"],
            ["machine_models.id"],
            name=op.f("fk_model_documents_machine_model_id_machine_models"),
        ),
        sa.PrimaryKeyConstraint("machine_model_id", "document_id", name=op.f("pk_model_documents")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_documents")
    op.drop_index(op.f("ix_machine_models_model_number"), table_name="machine_models")
    op.drop_table("machine_models")
    op.drop_index(op.f("ix_documents_document_type"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("brands")
    op.drop_table("providers")
    op.drop_table("manufacturers")
    # ### end Alembic commands ###
